# Generated by autoconf; do not edit.

if (NOT TARGET wolfssl::wolfssl)
  add_library(wolfssl::wolfssl UNKNOWN IMPORTED)

  set(_wolfssl_libdir "/usr/local/lib")
  set(_wolfssl_includedir "/usr/local/include")

  find_library(WOLFSSL_LIBRARY NAMES wolfssl PATHS "${_wolfssl_libdir}" NO_DEFAULT_PATH)
  if (NOT WOLFSSL_LIBRARY)
    find_library(WOLFSSL_LIBRARY NAMES wolfssl)
  endif()
  if (NOT WOLFSSL_LIBRARY)
    message(FATAL_ERROR "wolfssl library not found. Looked in: ${_wolfssl_libdir}")
  endif()

  set_target_properties(wolfssl::wolfssl PROPERTIES
    IMPORTED_LOCATION "${WOLFSSL_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${_wolfssl_includedir}"
  )

  if (1)
    set_property(TARGET wolfssl::wolfssl APPEND PROPERTY
      INTERFACE_LINK_LIBRARIES Threads::Threads
    )
  endif()
endif()
